language: go
sudo: required

os:
  - linux
  - osx

go:
  - "1.10.x"
  - master

osx_image: xcode9.1

matrix:
  fast_finish: true
  allow_failures:
    - go: master

script:
  - make test

services:
  - docker
